"use client";
import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import { FEATURED_STORY as S } from "@/lib/story";

type Mode = "text" | "audio" | "video";

const TABS: { key: Mode; label: string; sub: string }[] = [
  { key: "text",  label: "Text",  sub: "60-word summary" },
  { key: "audio", label: "Audio", sub: "AI voice · 15s" },
  { key: "video", label: "Video", sub: "AI anchor · 15s" },
];

export default function FormatSwitcher() {
  const [mode, setMode] = useState<Mode>("text");
  const [showEnglish, setShowEnglish] = useState(false);
  const audioRef = useRef<HTMLAudioElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);

  // Pause other media when switching modes
  useEffect(() => {
    if (mode !== "audio" && audioRef.current) {
      audioRef.current.pause();
      audioRef.current.currentTime = 0;
    }
    if (mode !== "video" && videoRef.current) {
      videoRef.current.pause();
    }
  }, [mode]);

  return (
    <section
      id="formats"
      className="relative border-t border-white/[0.06] py-20 sm:py-24 lg:py-32 overflow-hidden bg-black"
    >
      {/* Soft mesh */}
      <div
        aria-hidden
        className="absolute inset-0 -z-10"
        style={{
          background:
            "radial-gradient(ellipse 70% 50% at 50% 0%, rgba(230,72,30,0.10), transparent 60%), radial-gradient(ellipse 50% 40% at 80% 80%, rgba(45,106,79,0.06), transparent 60%), #000",
        }}
      />

      <div className="mx-auto max-w-[1280px] px-5 sm:px-6 lg:px-10">
        {/* Header */}
        <div className="grid lg:grid-cols-12 gap-8 lg:gap-10 mb-12 lg:mb-16">
          <div className="lg:col-span-7">
            <div className="eyebrow mb-5">One story in three formats</div>
            <h2 className="display fluid-h2 tracking-tightest text-balance">
              Read it.{" "}
              <span className="display-italic text-white/55">Hear it.</span>{" "}
              Watch it.
            </h2>
          </div>
          <div className="lg:col-span-4 lg:col-start-9 lg:pt-3">
            <p className="fluid-lead text-white/55">
              Same verified story. Text summary, AI voice, AI anchor video. All generated by the same pipeline. Toggle and compare.
            </p>
          </div>
        </div>

        {/* Card */}
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] backdrop-blur-sm overflow-hidden shadow-[0_30px_80px_-40px_rgba(0,0,0,0.8)]">
          {/* Tab bar */}
          <div className="flex items-center justify-between gap-4 px-4 sm:px-5 py-3 border-b border-white/[0.06] bg-black/30">
            <div className="flex items-center gap-1.5 sm:gap-2 overflow-x-auto -mx-1 px-1">
              {TABS.map((t) => {
                const active = mode === t.key;
                return (
                  <button
                    key={t.key}
                    onClick={() => setMode(t.key)}
                    className={`relative shrink-0 inline-flex items-center gap-2 px-3.5 sm:px-4 py-2 rounded-full text-[12px] sm:text-[13px] font-medium transition-all duration-300 ${
                      active
                        ? "bg-white text-black"
                        : "text-white/55 hover:text-white border border-white/10 hover:border-white/25"
                    }`}
                  >
                    <span
                      className={`w-1.5 h-1.5 rounded-full ${
                        active ? "bg-accent pulse-dot" : "bg-white/30"
                      }`}
                    />
                    {t.label}
                    <span
                      className={`hidden sm:inline mono text-[10px] tracking-[0.18em] uppercase ${
                        active ? "text-black/55" : "text-white/35"
                      }`}
                    >
                      {t.sub}
                    </span>
                  </button>
                );
              })}
            </div>
            <div className="hidden md:flex items-center gap-2 shrink-0">
              <span className="mono text-[10px] tracking-[0.22em] uppercase text-white/40">
                {S.publishedAgo}
              </span>
            </div>
          </div>

          {/* Story header strip — shared across modes */}
          <div className="px-5 sm:px-6 py-4 border-b border-white/[0.06] flex flex-wrap items-center gap-3 sm:gap-4 bg-black/20">
            <div className="flex items-center gap-2">
              <span className="bg-verified-soft-dark mono text-[10px] tracking-[0.18em] uppercase px-2.5 py-1 rounded-full inline-flex items-center gap-1.5">
                <span className="w-1 h-1 rounded-full bg-current" />
                Source verified
              </span>
              <span className="border border-white/15 mono text-[10px] tracking-[0.18em] uppercase px-2.5 py-1 rounded-full text-white/65">
                {S.language}
              </span>
              <span className="border border-white/15 mono text-[10px] tracking-[0.18em] uppercase px-2.5 py-1 rounded-full text-white/65">
                {S.category}
              </span>
            </div>
            <div className="display text-[15px] sm:text-[16px] text-white/85 ml-auto">
              {S.source}
            </div>
          </div>

          {/* Mode-specific body */}
          <div className="p-5 sm:p-7 lg:p-9 min-h-[280px] sm:min-h-[340px]">
            {mode === "text" && <TextMode showEnglish={showEnglish} setShowEnglish={setShowEnglish} />}
            {mode === "audio" && <AudioMode audioRef={audioRef} />}
            {mode === "video" && <VideoMode videoRef={videoRef} />}
          </div>

          {/* Footer flags */}
          <div className="px-5 sm:px-6 py-3 border-t border-white/[0.06] bg-black/30 flex flex-wrap items-center gap-2 sm:gap-3">
            <span className="mono text-[10px] tracking-[0.22em] uppercase text-white/40 mr-1">
              Provenance
            </span>
            {S.flags.map((f) => (
              <span
                key={f.label}
                className={`mono text-[10px] tracking-[0.18em] uppercase px-2.5 py-1 rounded-full inline-flex items-center gap-1.5 ${
                  f.tone === "verified"
                    ? "bg-verified-soft-dark"
                    : "border border-white/15 text-white/55"
                }`}
              >
                {f.tone === "verified" && (
                  <span className="w-1 h-1 rounded-full bg-current" />
                )}
                {f.label}
              </span>
            ))}
          </div>
        </div>

        <div className="mt-4 mono text-[10px] sm:text-[11px] tracking-[0.22em] uppercase text-white/45">
          Audio and video are demo previews · text mode is live in the app today
        </div>
      </div>
    </section>
  );
}

/* ─── Text mode ──────────────────────────────────────────────────────── */
function TextMode({
  showEnglish,
  setShowEnglish,
}: {
  showEnglish: boolean;
  setShowEnglish: (v: boolean) => void;
}) {
  return (
    <div className="grid lg:grid-cols-[1fr_auto] gap-6 lg:gap-10 items-start">
      <div>
        <div className="mono text-[10px] tracking-[0.25em] uppercase text-white/40 mb-3">
          60-word summary
        </div>
        <p className="text-[16px] sm:text-[17px] lg:text-[18px] leading-[1.6] text-white/90 max-w-[60ch]">
          {showEnglish ? S.summaryEn : S.summaryHi}
        </p>
        <div className="mt-5 mono text-[10px] tracking-[0.22em] uppercase text-white/40">
          {showEnglish ? "English translation" : "Original · हिन्दी"}
        </div>
      </div>
      <div className="flex lg:flex-col items-start gap-2 shrink-0">
        <button
          onClick={() => setShowEnglish(false)}
          className={`px-3 py-1.5 mono text-[10px] tracking-[0.18em] uppercase rounded-full transition-colors ${
            !showEnglish
              ? "bg-white text-black"
              : "border border-white/15 text-white/55 hover:text-white"
          }`}
        >
          हिन्दी
        </button>
        <button
          onClick={() => setShowEnglish(true)}
          className={`px-3 py-1.5 mono text-[10px] tracking-[0.18em] uppercase rounded-full transition-colors ${
            showEnglish
              ? "bg-white text-black"
              : "border border-white/15 text-white/55 hover:text-white"
          }`}
        >
          English
        </button>
      </div>
    </div>
  );
}

/* ─── Audio mode ─────────────────────────────────────────────────────── */
function AudioMode({ audioRef }: { audioRef: React.RefObject<HTMLAudioElement | null> }) {
  const [playing, setPlaying] = useState(false);
  const [progress, setProgress] = useState(0);

  const toggle = () => {
    const a = audioRef.current;
    if (!a) return;
    if (a.paused) a.play();
    else a.pause();
  };

  useEffect(() => {
    const a = audioRef.current;
    if (!a) return;
    const onPlay = () => setPlaying(true);
    const onPause = () => setPlaying(false);
    const onTime = () => setProgress((a.currentTime / (a.duration || 1)) * 100);
    a.addEventListener("play", onPlay);
    a.addEventListener("pause", onPause);
    a.addEventListener("timeupdate", onTime);
    a.addEventListener("ended", onPause);
    return () => {
      a.removeEventListener("play", onPlay);
      a.removeEventListener("pause", onPause);
      a.removeEventListener("timeupdate", onTime);
      a.removeEventListener("ended", onPause);
    };
  }, [audioRef]);

  // Faux waveform — deterministic so it doesn't jitter on rerenders
  const bars = Array.from({ length: 56 }, (_, i) => {
    const seed = Math.sin(i * 12.9898) * 43758.5453;
    const h = Math.abs(seed - Math.floor(seed)); // 0..1
    return 0.25 + h * 0.75;
  });

  return (
    <div className="flex flex-col gap-6 sm:gap-8">
      <div className="mono text-[10px] tracking-[0.25em] uppercase text-white/40">
        AI-generated voice · Hindi
      </div>

      <div className="flex items-center gap-5 sm:gap-7">
        <button
          onClick={toggle}
          aria-label={playing ? "Pause" : "Play"}
          className="shrink-0 w-14 h-14 sm:w-16 sm:h-16 rounded-full bg-white text-black flex items-center justify-center hover:bg-accent hover:text-white transition-colors"
        >
          {playing ? (
            <svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor">
              <rect x="5" y="3.5" width="3.5" height="13" rx="1" />
              <rect x="11.5" y="3.5" width="3.5" height="13" rx="1" />
            </svg>
          ) : (
            <svg width="22" height="22" viewBox="0 0 22 22" fill="currentColor">
              <path d="M6 3.5 L18 11 L6 18.5 Z" />
            </svg>
          )}
        </button>

        {/* Waveform */}
        <div className="flex-1 flex items-center gap-[3px] h-14 sm:h-16">
          {bars.map((b, i) => {
            const filled = (i / bars.length) * 100 < progress;
            return (
              <span
                key={i}
                className={`wave-bar block rounded-full ${
                  filled ? "bg-accent" : "bg-white/15"
                }`}
                style={{
                  width: 3,
                  height: `${b * 100}%`,
                  animationDelay: `${(i % 12) * 0.08}s`,
                  animationPlayState: playing ? "running" : "paused",
                  transform: !playing ? `scaleY(${b})` : undefined,
                }}
              />
            );
          })}
        </div>

        <div className="shrink-0 mono text-[11px] sm:text-[12px] tracking-wider text-white/55 tabular">
          0:{String(Math.floor((progress / 100) * 15)).padStart(2, "0")} / 0:15
        </div>
      </div>

      <p className="text-[14px] sm:text-[15px] text-white/55 leading-relaxed max-w-2xl">
        The same 60-word summary read by our AI voice in Hindi. The audio mode is built for commute and hands-free reading; full multi-language voice rollout in beta.
      </p>

      <audio ref={audioRef as React.RefObject<HTMLAudioElement>} preload="metadata" src="/story/unbiasly-story.mp3" />
    </div>
  );
}

/* ─── Video mode ─────────────────────────────────────────────────────── */
function VideoMode({ videoRef }: { videoRef: React.RefObject<HTMLVideoElement | null> }) {
  return (
    <div className="grid lg:grid-cols-[1.05fr_1fr] gap-6 lg:gap-10 items-start">
      <div className="relative rounded-xl overflow-hidden border border-white/10 bg-black aspect-[1040/864] max-w-md mx-auto lg:mx-0">
        <video
          ref={videoRef as React.RefObject<HTMLVideoElement>}
          controls
          playsInline
          preload="metadata"
          poster="/story/unbiasly-story-poster.jpg"
          className="block w-full h-full object-cover"
        >
          <source src="/story/unbiasly-story.webm" type="video/webm" />
          <source src="/story/unbiasly-story.mp4" type="video/mp4" />
        </video>
        <div className="absolute top-3 left-3 mono text-[9px] tracking-[0.22em] uppercase bg-black/60 backdrop-blur-sm text-white/85 px-2 py-1 rounded-full border border-white/15">
          AI-generated
        </div>
      </div>

      <div className="flex flex-col gap-5 lg:pt-2">
        <div>
          <div className="mono text-[10px] tracking-[0.25em] uppercase text-white/40 mb-2">
            AI anchor · 15-second read
          </div>
          <p className="text-[15px] sm:text-[16px] lg:text-[17px] leading-[1.55] text-white/85">
            The same verified story, delivered as a short AI anchor video. Same source attribution, same provenance footer, just a different format for readers who prefer to watch.
          </p>
        </div>

        <div className="grid grid-cols-2 gap-px bg-white/[0.06] rounded-xl overflow-hidden border border-white/[0.06]">
          <Stat label="Generation time" value="~12s" />
          <Stat label="Cost per video" value="Sub-cent" />
          <Stat label="Languages" value="3 live" />
          <Stat label="Status" value="Beta" accent />
        </div>
      </div>
    </div>
  );
}

function Stat({ label, value, accent }: { label: string; value: string; accent?: boolean }) {
  return (
    <div className="bg-black p-4 sm:p-5">
      <div className="mono text-[9px] tracking-[0.25em] uppercase text-white/40 mb-2">
        {label}
      </div>
      <div className={`display text-[22px] sm:text-[26px] leading-none ${accent ? "text-accent" : "text-white"}`}>
        {value}
      </div>
    </div>
  );
}
